name: pipeline

on:
  push:
    branches:
      - dev
jobs:
  massive_ci_pipeline:
    runs-on: ubuntu-latest
    env:
      DB: ${{ secrets.DB }}
      HAL_PW: ${{ secrets.HAL_PW }}
      TEST_PW: ${{ secrets.TEST_PW }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "20"
      - name: Setup environment
        run: |
          echo "DB=${DB}" >> .env
          echo "HAL_PW=${HAL_PW}" >> .env
          echo "TEST_PW=${HAL_PW}" >> .env
      - name: Install dependencies
        run: npm install
      - name: Install frontend dependencies
        run: |
          cd frontend
          npm install
      - name: Check style
        run: npm run lint
      - name: ApiTest
        run: npm test
